version: 0.2
phases:
  install:
    commands:
    - pip install -r requirements.txt -t build/
    - cp -R monitor lambda.py app.py build/
    - aws cloudformation package --kms-key-id 1a6849b9-d32a-4828-bc0a-a46e6e90ddda --template-file sam.template --s3-bucket codepipeline-eu-central-1-733964139140 --output-template-file sam-output.yaml
artifacts:
  type: zip
  files:
    - sam-output.yaml
