version: 0.2
phases:
  install:
    commands:
    - pip install -r requirements.txt -t build/
    - cp -R monitor lambda.py build/
    - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-eu-central-1-733964139140 --output-template-file sam-output.yaml
artifacts:
  type: zip
  files:
  - sam-output.yaml

