version: 0.2
phases:
  install:
    commands:
    - pip install -r requirements.txt -t build/
    - cp -R monitor lambda.py build/
    - aws cloudformation package --template-file template.yaml --s3-bucket lambda-finhubmonitor --output-template-file sam_output.yaml
artifacts:
  type: zip
  files:
  - sam_output.yaml
