version: 0.2
phases:
  install:
    commands:
    - pip install -r requirements.txt -t build/
    - cp -R monitor lambda.py build/
    - aws cloudformation package --kms-key-id aws/s3 --template-file template.yaml --s3-bucket codepipeline-finhubmonitor --output-template-file sam-output.yaml
artifacts:
  type: zip
  files:
  - sam-output.yaml

